version: '3'

services:
  shabe:
    build:
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      # Uncomment and set your OpenAI API key if you want translation support
      # - OPENAI_API_KEY=your_api_key_here
